openapi: 3.0.1
info:
  title: taoTestPreview API
  description: Stands for TAO test Previewer API.
  version: 1.0.0
servers:
  - url: '{server}'
    variables:
      server:
        default: https://community.docker.localhost/
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: tao_community
  responses:
    init:
      description: Good response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/testInit'
    badResponse:
      description: If something went wrong
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
  schemas:
    testInit:
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            success:
              type: boolean
            testData:
              $ref: '#/components/schemas/testData'
            testContext:
              $ref: '#/components/schemas/testContext'
            testMap:
              $ref: '#/components/schemas/testMap'
            toolStates:
              description: the current tools states
              type: array
              items:
                type: integer
            lastStoreId:
              description: Checks the storeId request parameter and returns the last store id if set, false otherwise
              type: string
            messages:
              type: array
              items:
                type: integer
    testData:
      description: test definition data
      deprecated: true
      type: object
      properties:
        title:
          type: string
        identifier:
          type: string
        className:
          type: string
        toolName:
          type: string
        exclusivelyLinear:
          type: boolean
        hasTimeLimits:
          type: boolean
        states:
          type: object
        itemStates:
          type: object
        config:
          type: object
    testContext:
      description: test context object
      type: object
    testMap:
      description: the map of the test items
      type: object
    errorResponse:
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 400
        message:
          type: string

security:
  - cookieAuth: []

paths:
  /taoQtiTestPreviewer/TestPreviewer/init:
    get:
      parameters:
        - in: query
          name: testUri
          schema:
            type: string
          required: true
          example: 'https%3A%2F%2Fcommunity.docker.localhost%2Fontologies%2Ftao.rdf%23i5efb42fced1ce7064796c08b38ee176'
          description: Url encoded test identifier

      summary: Returns a test map
      responses:
        '200':
          $ref: '#/components/responses/init'
        '500':
          $ref: '#/components/responses/badResponse'