openapi: 3.0.1
info:
  title: Media Manager API
  description: 'TAO Media Manager API'
  version: v1

paths:
  /taoMediaManager/SharedStimulus/create:
    post:
      summary: Create a default shared stimulus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SharedStimulus'
      responses:
        204:
          $ref: '#/components/responses/SharedStimulusCreatedResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
  /taoMediaManager/SharedStimulus/get:
    get:
      summary: Get a shared stimulus
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: The shared stimulus id
      responses:
        200:
          $ref: '#/components/responses/SharedStimulusCreatedResponse'
        400:
          $ref: '#/components/responses/BadRequestResponse'
        500:
          $ref: '#/components/responses/InternalServerErrorResponse'
components:
  schemas:
    SharedStimulus:
      type: object
      properties:
        classId:
          type: string
          example: 'http://tao.docker.localhost/tao.rdf#i5e89a2063326711164b1a816b433b1ec'
        languageId:
          type: string
          example: 'http://www.tao.lu/Ontologies/TAO.rdf#Langen-US'
        name:
          type: string
          example: 'New Passage'
      required:
        - classId
    SharedStimulusCreated:
      allOf:
        - $ref: '#/components/schemas/SharedStimulus'
        - type: object
          properties:
            id:
              type: string
              example: "http://tao.docker.localhost/tao.rdf#i5e89a2063326711164b1a816b433b1ec"
            body:
              type: string
              example: '{
                          "success": true,
                          "data": {
                            "serial": "i5ec3f09d28d19",
                            "qtiClass": "include",
                            "attributes": {},
                            "body": {
                              "serial": "i5ec3f09d28ef1",
                              "body": "\n",
                              "elements": {}
                            }
                          }
                        }'
    SharedStimulusCreatedResponse:
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/SharedStimulusCreated'
    ErrorResponse:
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 400
        message:
          type: string
  responses:
    SharedStimulusCreatedResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SharedStimulusCreatedResponse'
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerErrorResponse:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
