swagger: '2.0'
info:
  description: Tasks API
  version: 1.0.0
  title: Tasks API
basePath: /act.dev
schemes:
  - http
  - https
paths:
  /taoTaskQueue/RestTask/get:
    get:
      tags:
        - Get Task
      summary: Get Task
      description: Get Task
      operationId: GetTask
      parameters:
        - name: taskId
          in: query
          description: Task id identifier
          required: true
          type: string
          format: int64
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
              data:
                $ref: '#/definitions/TaskLog'
              errorCode:
                type: string
              errorMsg:
               type: string
        '400':
          description: Bad request if you send invalid parameters.
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
  /taoTaskQueue/RestTask/getAll:
    get:
      tags:
        - Get Tasks
      summary: Get Tasks
      description: Get Tasks
      operationId: GetTasks
      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          type: integer
          format: int64
        - name: offset
          in: query
          description: Offset
          required: false
          type: integer
          format: int64
        - name: reportIncluded
          in: query
          description: Should report be included in the response or not?
          required: false
          type: integer
          format: int64
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
              data:
                type: array
                items:
                  $ref: '#/definitions/TaskLog'
              errorCode:
                type: string
              errorMsg:
               type: string
        '400':
          description: Bad request if you send invalid parameters.
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
  /taoTaskQueue/RestTask/stats:
    get:
      tags:
        - Get Tasks Status
      summary: Get Tasks Status
      description: Get Tasks Status
      operationId: GetTasksStatus
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
              data:
                $ref: '#/definitions/TaskStatus'
              errorCode:
                type: string
              errorMsg:
               type: string
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
  /taoTaskQueue/RestTask/archive:
    post:
      tags:
        - Archive Task
      summary: Archive Task
      description: Archive Task
      operationId: ArchiveTask
      parameters:
        - name: taskId
          in: formData
          description: Task id to archive
          required: true
          type: string
          format: int64
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            properties:
              success:
                type: boolean
              errorCode:
                type: string
              errorMsg:
               type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Task not found
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
definitions:
  TaskStatus:
    type: object
    required:
      - numberOfTasksCompleted
      - numberOfTasksFailed
      - numberOfTasksInProgress
    properties:
      numberOfTasksCompleted:
        type: integer
        example: 10
      numberOfTasksFailed:
        type: integer
        example: 10
      numberOfTasksInProgress:
        type: integer
        example: 10
  TaskLog:
    type: object
    required:
      - id
      - taskName
      - taskLabel
    properties:
      id:
        type: string
        example: 'https://nccersso.taocloud.org/nccer.rdf#i150764040443513560'
      taskName:
        type: string
        example: PrintOrder
      taskLabel:
        type: string
        example: Booklet for Test 2
      status:
        type: string
        enum:
        - in_progress
        - completed
        - failed
      statusLabel:
        type: string
        example: In Progress
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      report:
        $ref: '#/definitions/TaskReport'
      hasFile:
        type: boolean
        example: false
      category:
        type: string
        example: export
  TaskReport:
    type: object
    properties:
      type:
        type: string
        example: info
      message:
        type: string
        example: Running
      data:
        type: string
        example: Some specific report data
      children:
        type: array
        items:
          $ref: '#/definitions/TaskReport'
  ErrorModel:
    type: object
    properties:
      success:
        type: boolean
      version:
        type: string
      errorCode:
        type: string
      errorMsg:
        type: string